// Test scenarios extracted from scoring.test.ts — used by both tests and the scoring demo UI.
//
// Each scenario defines a hand, declared melds, expected fan results, and win context.

import type { WinContext, ScoringMeld } from "./types.js";
import { tileIndex, parseMelds } from "./tile-parser.js";

export interface TestScenario {
  name: string;
  hand: string;           // space-separated tile tokens
  melds: string[];        // meld notation strings
  expected: string[];     // expected fan names (repeat for multiples)
  ctx: ScenarioContext;
}

export interface ScenarioContext {
  winTile: string;
  winSource?: "selfDraw" | "discard" | "kongDraw" | "robbingKong";
  seatWind?: "east" | "south" | "west" | "north";
  roundWind?: "east" | "south" | "west" | "north";
  isDealer?: boolean;
  wallCount?: number;
  bonusTileCount?: number;
  winTileVisibleCount?: number;
}

/** Build a WinContext from a scenario context. */
export function buildWinContext(tc: ScenarioContext, declaredMeldCount: number): { winTileIdx: number; context: WinContext } {
  const winTileIdx = tileIndex(tc.winTile);
  return {
    winTileIdx,
    context: {
      winTile: winTileIdx,
      winSource: tc.winSource ?? "selfDraw",
      seatWind: tc.seatWind ?? "east",
      roundWind: tc.roundWind ?? "east",
      seatIndex: 0,
      isDealer: tc.isDealer ?? true,
      wallCount: tc.wallCount ?? 40,
      bonusTileCount: tc.bonusTileCount ?? 0,
      isKongDraw: (tc.winSource ?? "selfDraw") === "kongDraw",
      isRobbingKong: (tc.winSource ?? "selfDraw") === "robbingKong",
      declaredMeldCount,
      winTileVisibleCount: tc.winTileVisibleCount ?? 0,
    },
  };
}

export const TEST_SCENARIOS: TestScenario[] = [
  { name: "大四喜1", hand: "E E E S S S W W W N N N 9s", melds: [], expected: ["大四喜", "四暗刻", "混幺九", "混一色", "单钓将", "不求人"], ctx: { winTile: "9s" } },
  { name: "大四喜2", hand: "E E E S S S W W W N N N 9s", melds: [], expected: ["大四喜", "四暗刻", "混幺九", "混一色", "单钓将"], ctx: { winTile: "9s", winSource: "discard"} },
  { name: "大四喜3", hand: "S S S W W W N N N 9s", melds: ["p(E E E)"], expected: ["大四喜", "混幺九", "三暗刻", "混一色", "单钓将"], ctx: { winTile: "9s", winSource: "discard"} },
  { name: "大四喜4", hand: "S S S W W W N N N Z", melds: ["p(E E E)"], expected: ["大四喜", "字一色", "三暗刻", "单钓将"], ctx: { winTile: "Z", winSource: "discard"} },
  { name: "大三元1", hand: "Z Z Z F F F B B B 1m 2m 3m 9s", melds: [], expected: ["大三元", "三暗刻", "全带幺九", "门前清", "缺一门", "单钓将"], ctx: { winTile: "9s", winSource: "discard" } },
  { name: "大三元2", hand: "Z Z Z F F F B B 1m 2m 3m 9s 9s", melds: [], expected: ["大三元", "全带幺九", "门前清", "双暗刻", "缺一门"], ctx: { winTile: "B", winSource: "discard" } },
  { name: "大三元3", hand: "Z Z Z F F F B B B E E N N", melds: [], expected: ["大三元", "字一色", "三暗刻", "圈风刻", "门风刻", "门前清"], ctx: { winTile: "E", winSource: "discard" } },
  { name: "绿一色1", hand: "2s 3s 4s 4s 4s 4s 6s 6s 6s F F 8s 8s", melds: [], expected: ["绿一色", "箭刻", "门前清", "四归一", "双暗刻"], ctx: { winTile: "F", winSource: "discard" } },
  { name: "绿一色2", hand: "2s 2s 2s 3s 3s 3s 4s 4s 4s 8s 8s 6s 6s", melds: [], expected: ["绿一色", "清一色", "一色三节高", "三暗刻", "碰碰和", "门前清", "断幺九"], ctx: { winTile: "8s", winSource: "discard" } },
  { name: "绿一色3", hand: "3s 3s 3s 4s 4s 4s 8s 8s 6s 6s", melds: ["p(2s 2s 2s)"], expected: ["绿一色", "清一色", "一色三节高", "碰碰和", "双暗刻", "断幺九"], ctx: { winTile: "8s", winSource: "discard" } },
  { name: "九莲宝灯1", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "清龙", "四归一"], ctx: { winTile: "9m", winSource: "discard" } },
  { name: "九莲宝灯2", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "清龙", "四归一", "自摸"], ctx: { winTile: "9m" } },
  { name: "九莲宝灯3", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "双暗刻", "连六", "幺九刻"], ctx: { winTile: "8m", winSource: "discard" } },
  { name: "九莲宝灯4", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "双暗刻", "连六", "幺九刻", "自摸"], ctx: { winTile: "8m" } },
  { name: "九莲宝灯5", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "连六"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "九莲宝灯6", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "连六", "自摸"], ctx: { winTile: "7m" } },
  { name: "九莲宝灯7", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "双暗刻", "幺九刻"], ctx: { winTile: "5m", winSource: "discard" } },
  { name: "九莲宝灯8", hand: "1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m 9m", melds: [], expected: ["九莲宝灯", "双暗刻", "幺九刻", "自摸"], ctx: { winTile: "5m" } },
  { name: "九莲宝灯9", hand: "1m 1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m", melds: [], expected: ["清一色", "清龙", "门前清", "四归一", "幺九刻"], ctx: { winTile: "9m", winSource: "discard" } },
  { name: "九莲宝灯10", hand: "1m 1m 1m 1m 2m 3m 4m 5m 6m 7m 8m 9m 9m", melds: [], expected: ["清一色", "清龙", "不求人", "四归一", "幺九刻"], ctx: { winTile: "9m" } },
  { name: "四杠1", hand: "7m", melds: ["k(7s 7s 7s 7s)", "k(8m 8m 8m 8m)", "k(9p 9p 9p 9p)", "k(9s 9s 9s 9s)"], expected: ["四杠", "全大", "三色三节高", "全求人", "双同刻", "幺九刻", "幺九刻"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "四杠2", hand: "7m", melds: ["k(7s 7s 7s 7s)", "!k(8m 8m 8m 8m)", "k(9p 9p 9p 9p)", "k(9s 9s 9s 9s)"], expected: ["四杠", "全大", "三色三节高", "暗杠", "双同刻", "幺九刻", "幺九刻"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "四杠3", hand: "7m", melds: ["k(7s 7s 7s 7s)", "!k(8m 8m 8m 8m)", "!k(9p 9p 9p 9p)", "k(9s 9s 9s 9s)"], expected: ["四杠", "全大", "三色三节高", "双暗杠", "双同刻", "幺九刻", "幺九刻"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "四杠4", hand: "7m", melds: ["k(7s 7s 7s 7s)", "!k(8m 8m 8m 8m)", "!k(9p 9p 9p 9p)", "k(9s 9s 9s 9s)"], expected: ["四杠", "全大", "三色三节高", "双暗杠", "双同刻", "幺九刻", "幺九刻", "自摸"], ctx: { winTile: "7m" } },
  { name: "四杠5", hand: "W", melds: ["k(1m 1m 1m 1m)", "k(1p 1p 1p 1p)", "k(1s 1s 1s 1s)", "k(F F F F)"], expected: ["四杠", "混幺九", "三同刻", "五门齐", "全求人", "箭刻"], ctx: { winTile: "W", winSource: "discard" } },
  { name: "四杠6", hand: "W", melds: ["k(1m 1m 1m 1m)", "k(1p 1p 1p 1p)", "k(1s 1s 1s 1s)", "k(F F F F)"], expected: ["四杠", "混幺九", "三同刻", "五门齐", "箭刻", "自摸"], ctx: { winTile: "W" } },
  { name: "四杠7", hand: "W", melds: ["!k(1m 1m 1m 1m)", "!k(1p 1p 1p 1p)", "!k(1s 1s 1s 1s)", "!k(F F F F)"], expected: ["四杠", "四暗刻", "混幺九", "三同刻", "五门齐", "箭刻", "不求人"], ctx: { winTile: "W" } },
  { name: "四杠8", hand: "W", melds: ["!k(1m 1m 1m 1m)", "!k(1p 1p 1p 1p)", "!k(1s 1s 1s 1s)", "!k(F F F F)"], expected: ["四杠", "四暗刻", "混幺九", "三同刻", "五门齐", "箭刻"], ctx: { winTile: "W", winSource: "discard" } },
  { name: "连七对1", hand: "1m 1m 2m 2m 3m 3m 4m 4m 5m 5m 6m 6m 7m", melds: [], expected: ["连七对"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "连七对2", hand: "2m 2m 3m 3m 4m 4m 5m 5m 6m 6m 7m 7m 8m", melds: [], expected: ["连七对", "自摸", "断幺九"], ctx: { winTile: "8m" } },
  { name: "十三幺1", hand: "1m 1m 1p 9p 1s 9s E S W N Z F B", melds: [], expected: ["十三幺", "自摸"], ctx: { winTile: "9m" } },
  { name: "十三幺2", hand: "1m 1m 1p 9p 1s 9s E S W N Z F B", melds: [], expected: ["十三幺"], ctx: { winTile: "9m", winSource: "discard" } },
  { name: "十三幺3", hand: "1m 9m 1p 9p 1s 9s E S W N Z F B", melds: [], expected: ["十三幺"], ctx: { winTile: "1m", winSource: "discard" } },
  { name: "清幺九1", hand: "1m 1m 1m 1p 1p 1p 9m 9m 9m 9s 9s 9s 1s", melds: [], expected: ["清幺九", "四暗刻", "双同刻", "单钓将", "不求人"], ctx: { winTile: "1s" } },
  { name: "清幺九2", hand: "1m 1m 1p 1p 1s 1s 9m 9m 9p 9p 9s 9s 9s", melds: [], expected: ["清幺九", "七对", "不求人"], ctx: { winTile: "9s" } },
  { name: "清幺九3", hand: "1m 1m 1p 1p 1s 1s 9m 9m 9p 9p 9s 9s 9s", melds: [], expected: ["清幺九", "七对"], ctx: { winTile: "9s", winSource: "discard"} },
  { name: "小四喜1", hand: "E E E S S S W W W 9s 9s N N", melds: [], expected: ["小四喜", "四暗刻", "混幺九", "混一色", "圈风刻", "门风刻", "不求人"], ctx: { winTile: "9s" } },
  { name: "小四喜2", hand: "S S S W W W 9s 9s N N", melds: ["p(E E E)"], expected: ["小四喜", "混幺九", "混一色", "三暗刻", "圈风刻", "门风刻", "自摸"], ctx: { winTile: "9s" } },
  { name: "小四喜3", hand: "W W W 9s 9s N N", melds: ["p(E E E)", "p(S S S)"], expected: ["小四喜", "混幺九", "混一色", "双暗刻", "门风刻", "自摸"], ctx: { winTile: "9s", roundWind: "north"} },
  { name: "小四喜4", hand: "W W W 9s 9s N N", melds: ["p(E E E)", "p(S S S)"], expected: ["小四喜", "混幺九", "混一色", "门风刻"], ctx: { winTile: "9s", roundWind: "north", winSource: "discard"} },
  { name: "小四喜5", hand: "9s 9s N N", melds: ["p(E E E)", "p(S S S)", "p(W W W)"], expected: ["小四喜", "混幺九", "混一色", "自摸"], ctx: { winTile: "9s", roundWind: "north", seatWind: "north"} },
  { name: "小四喜6", hand: "8s 8s N N", melds: ["p(E E E)", "p(S S S)", "p(W W W)"], expected: ["小四喜", "碰碰和", "混一色", "自摸"], ctx: { winTile: "8s", roundWind: "north", seatWind: "north"} },
  { name: "小三元1", hand: "Z Z Z F F F 1p 1p 1p 1s 1s 1s B", melds: [], expected: ["小三元", "四暗刻", "混幺九", "不求人", "双同刻", "缺一门", "单钓将"], ctx: { winTile: "B" } },
  { name: "小三元2", hand: "Z Z Z F F F 1p 2p 3p 7p 8p 9p B", melds: [], expected: ["小三元", "混一色", "全带幺九", "双暗刻", "老少副", "不求人", "单钓将"], ctx: { winTile: "B" } },
  { name: "小三元3", hand: "Z Z Z F F F 1p 2p 3p 4s 5s 6s B", melds: [], expected: ["小三元", "双暗刻", "缺一门", "不求人", "单钓将"], ctx: { winTile: "B" } },
  { name: "小三元4", hand: "F F F 1p 2p 3p 4p 5p 6p B", melds: ["p(Z Z Z)"], expected: ["小三元", "混一色", "连六", "单钓将", "自摸"], ctx: { winTile: "B" } },
  { name: "字一色1", hand: "E E E S S Z Z Z F F F W W", melds: [], expected: ["字一色", "三暗刻", "双箭刻", "圈风刻", "门风刻", "门前清"], ctx: { winTile: "S", winSource: "discard" } },
  { name: "字一色2", hand: "S S W W", melds: ["p(E E E)", "p(Z Z Z)", "p(F F F)"], expected: ["字一色", "双箭刻", "圈风刻", "门风刻"], ctx: { winTile: "S", winSource: "discard" } },
  { name: "字一色3", hand: "S S W W", melds: ["p(E E E)", "p(Z Z Z)", "p(F F F)"], expected: ["字一色", "双箭刻", "圈风刻", "门风刻", "自摸"], ctx: { winTile: "S" } },
  { name: "四暗刻1", hand: "1m 1m 1m 5p 5p 5p 9s 9s 9s 3m 3m 3m 7p", melds: [], expected: ["四暗刻", "幺九刻", "幺九刻", "无字", "不求人"], ctx: { winTile: "7p" } },
  { name: "四暗刻2", hand: "1m 1m 1m 5p 5p 5p 9s 9s 9s 3m 3m 3m 7p", melds: [], expected: ["四暗刻", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "7p", winSource: "discard" } },
  { name: "四暗刻3", hand: "7p", melds: ["!k(1m 1m 1m 1m)", "!k(5p 5p 5p 5p)", "!k(9s 9s 9s 9s)", "!k(6s 6s 6s 6s)"], expected: ["四杠", "四暗刻", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "7p", winSource: "discard" } },
  { name: "四暗刻4", hand: "7p", melds: ["!k(1m 1m 1m 1m)", "!k(5p 5p 5p 5p)", "!k(9s 9s 9s 9s)", "!k(6s 6s 6s 6s)"], expected: ["四杠", "四暗刻", "不求人", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "7p" } },
  { name: "四暗刻5", hand: "7p 1m 1m 1m", melds: ["!k(5p 5p 5p 5p)", "!k(9s 9s 9s 9s)", "!k(6s 6s 6s 6s)"], expected: ["四暗刻", "三杠", "不求人", "幺九刻", "幺九刻", "无字", "单钓将"], ctx: { winTile: "7p" } },
  { name: "四暗刻6", hand: "7p 1m 1m 1m 5p 5p 5p", melds: ["!k(9s 9s 9s 9s)", "!k(6s 6s 6s 6s)"], expected: ["四暗刻", "双暗杠", "不求人", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "7p" } },
  { name: "四暗刻7", hand: "7p 1m 1m 1m 5p 5p 5p 9s 9s 9s", melds: ["!k(6s 6s 6s 6s)"], expected: ["四暗刻", "暗杠", "不求人", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "7p" } },
  { name: "一色双龙会1", hand: "1s 2s 3s 7s 8s 9s 1s 2s 3s 7s 8s 5s 5s", melds: [], expected: ["一色双龙会", "不求人"], ctx: { winTile: "9s" } },
  { name: "一色双龙会2", hand: "1s 2s 3s 7s 8s 9s 1s 2s 3s 7s 8s 5s 5s", melds: [], expected: ["一色双龙会", "门前清"], ctx: { winTile: "9s", winSource: "discard" } },
  { name: "一色双龙会3", hand: "1s 2s 3s 7s 8s 9s 1s 2s 3s 7s 8s 9s 5s", melds: [], expected: ["一色双龙会", "门前清", "单钓将"], ctx: { winTile: "5s", winSource: "discard" } },
  { name: "一色四同顺1", hand: "2s 3s 4s 2s 3s 4s 2s 3s 4s 2s 3s 4s 8s", melds: [], expected: ["绿一色", "一色四同顺", "清一色", "不求人", "平和", "断幺九", "单钓将"], ctx: { winTile: "8s" } },
  { name: "一色四同顺2", hand: "2s 3s 4s 2s 3s 4s 2s 3s 4s 2s 3s 8s 8s", melds: [], expected: ["绿一色", "一色四同顺", "清一色", "门前清", "平和", "断幺九"], ctx: { winTile: "4s", winSource: "discard" } },
  { name: "一色四同顺3", hand: "2s 3s 4s 2s 3s 4s 2s 3s 8s 8s", melds: ["c(2s 3s 4s)"], expected: ["绿一色", "一色四同顺", "清一色", "平和", "断幺九"], ctx: { winTile: "4s", winSource: "discard" } },
  { name: "一色四节高1", hand: "1p 1p 1p 2p 2p 2p 3p 3p 3p 4p 4p 4p 2s", melds: [], expected: ["四暗刻", "一色四节高", "小于五", "推不倒", "不求人", "幺九刻", "单钓将"], ctx: { winTile: "2s" } },
  { name: "一色四节高2", hand: "4p 4p 4p 2s", melds: ["p(1p 1p 1p)", "p(2p 2p 2p)", "p(3p 3p 3p)"], expected: ["一色四节高", "小于五", "推不倒", "自摸", "幺九刻", "单钓将"], ctx: { winTile: "2s" } },
  { name: "一色四节高3", hand: "4p 4p 2s 2s", melds: ["p(1p 1p 1p)", "p(2p 2p 2p)", "p(3p 3p 3p)"], expected: ["一色四节高", "小于五", "推不倒", "自摸", "幺九刻"], ctx: { winTile: "4p" } },
  { name: "一色四节高4", hand: "2s", melds: ["p(1p 1p 1p)", "p(2p 2p 2p)", "p(3p 3p 3p)", "p(4p 4p 4p)"], expected: ["一色四节高", "小于五", "推不倒", "全求人", "幺九刻"], ctx: { winTile: "2s", winSource: "discard" } },
  { name: "一色四步高1", hand: "2m 3m 4m 3m 4m 5m 4m 5m 6m 5m 6m N N", melds: [], expected: ["一色四步高", "混一色", "不求人"], ctx: { winTile: "7m" } },
  { name: "一色四步高2", hand: "2m 3m 4m 3m 4m 5m 4m 5m 6m 5m 7m N N", melds: [], expected: ["一色四步高", "混一色", "门前清"], ctx: { winTile: "6m", winSource: "discard" } },
  { name: "一色四步高3", hand: "1p 2p 3p 3p 4p 5p 5p 6p 7p 7p 8p 9p 9s", melds: [], expected: ["一色四步高", "不求人", "平和", "缺一门", "单钓将"], ctx: { winTile: "9s" } },
  { name: "一色四步高4", hand: "1p 3p 3p 4p 5p 5p 6p 7p 7p 8p 9p 9s 9s", melds: [], expected: ["一色四步高", "门前清", "平和", "缺一门", "坎张"], ctx: { winTile: "2p", winSource: "discard" } },
  { name: "一色四步高5", hand: "1p 2p 3p 4p 5p 5p 6p 7p 7p 8p 9p 9s 9s", melds: [], expected: ["一色四步高", "门前清", "平和", "缺一门"], ctx: { winTile: "3p", winSource: "discard" } },
  { name: "三杠1", hand: "1m 2m 4p 4p", melds: ["k(2s 2s 2s 2s)", "!k(3p 3p 3p 3p)", "k(4m 4m 4m 4m)"], expected: ["三杠", "小于五", "三色三节高", "边张", "自摸"], ctx: { winTile: "3m" } },
  { name: "三杠2", hand: "1m 2m 4p 4p", melds: ["k(2s 2s 2s 2s)", "k(3p 3p 3p 3p)", "k(4m 4m 4m 4m)"], expected: ["三杠", "小于五", "三色三节高", "边张", "自摸"], ctx: { winTile: "3m" } },
  { name: "三杠3", hand: "1m 2m 4p 4p", melds: ["k(2s 2s 2s 2s)", "!k(3p 3p 3p 3p)", "!k(4m 4m 4m 4m)"], expected: ["三杠", "小于五", "三色三节高", "双暗刻", "边张", "自摸"], ctx: { winTile: "3m" } },
  { name: "混幺九1", hand: "1m 1m 1m 1p 1p 1p 1s 1s 1s B B E E", melds: [], expected: ["四暗刻", "混幺九", "三同刻", "五门齐", "不求人", "箭刻"], ctx: { winTile: "B" } },
  { name: "混幺九2", hand: "1m 1m 1p 1p 9p 9p E E E E S S F", melds: [], expected: ["混幺九", "七对", "四归一", "缺一门"], ctx: { winTile: "F", winSource: "discard" } },
  { name: "七对1", hand: "1m 1m 6m 6m 7m 7m 4p 4p 9s 9s S S F", melds: [], expected: ["七对", "五门齐", "不求人"], ctx: { winTile: "F" } },
  { name: "七对2", hand: "1m 1m 6m 6m 7m 7m 4p 4p 9s 9s S S F", melds: [], expected: ["七对", "五门齐"], ctx: { winTile: "F", winSource: "discard" } },
  { name: "七对3", hand: "2s 2s 2s 2s 4s 4s 4s 4s 6s 6s 6s 8s 8s", melds: [], expected: ["绿一色", "七对", "清一色", "推不倒", "断幺九"], ctx: { winTile: "6s", winSource: "discard" } },
  { name: "七星不靠1", hand: "1m 4m 2s 8s 3p 6p 9p E S W N Z F", melds: [], expected: ["七星不靠", "自摸"], ctx: { winTile: "B" } },
  { name: "七星不靠2", hand: "1m 4m 2s 8s 3p 6p E S W N Z F B", melds: [], expected: ["七星不靠"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "七星不靠3", hand: "4s 7s 2p 8p 6m 9m E S W N Z F B", melds: [], expected: ["七星不靠"], ctx: { winTile: "5p", winSource: "discard" } },
  { name: "全双刻1", hand: "2m 2m 2m 8p 8p 8p 6s 6s 6s 8s 8s 8s 4s", melds: [], expected: ["四暗刻", "全双刻", "不求人", "双同刻"], ctx: { winTile: "4s" } },
  { name: "全双刻2", hand: "2p 2p 2p 8p 8p 8p 6s 6s 6s 8s 8s 8s 4s", melds: [], expected: ["四暗刻", "全双刻", "推不倒", "不求人", "双同刻"], ctx: { winTile: "4s" } },
  { name: "全双刻3", hand: "6s 6s 6s 8s 8s 8s 4s", melds: ["p(2p 2p 2p)", "p(8p 8p 8p)"], expected: ["双暗刻", "全双刻", "推不倒", "自摸", "双同刻"], ctx: { winTile: "4s" } },
  { name: "全双刻4", hand: "8s 8s 8s 4s", melds: ["p(2p 2p 2p)", "p(8p 8p 8p)", "p(6s 6s 6s)"], expected: ["单钓将", "全双刻", "推不倒", "自摸", "双同刻"], ctx: { winTile: "4s" } },
  { name: "清一色1", hand: "1m 2m 3m 1m 2m 3m 4m 5m 6m 7m 8m 9m 1m", melds: [], expected: ["清一色", "清龙", "不求人", "平和", "四归一", "一般高"], ctx: { winTile: "1m" } },
  { name: "清一色2", hand: "1m 2m 3m 1m 2m 3m 4m 5m 6m 7m 8m 9m 1m", melds: [], expected: ["清一色", "清龙", "门前清", "平和", "四归一", "一般高"], ctx: { winTile: "1m", winSource: "discard" } },
  { name: "清一色3", hand: "1m 2m 3m 4m 5m 6m 7m 8m 9m 1m", melds: ["c(1m 2m 3m)"], expected: ["清一色", "清龙", "平和", "四归一", "一般高"], ctx: { winTile: "1m", winSource: "discard" } },
  { name: "清一色4", hand: "1m 2m 3m 4m 5m 6m 7m 8m 9m 1m", melds: ["p(2m 2m 2m)"], expected: ["清一色", "清龙", "四归一"], ctx: { winTile: "1m", winSource: "discard" } },
  { name: "一色三同顺1", hand: "1p 2p 3p 1p 2p 3p 1m 2m 3m 1m", melds: ["c(1p 2p 3p)"], expected: ["一色三同顺", "全小", "全带幺九", "平和", "喜相逢", "缺一门", "自摸"], ctx: { winTile: "1m" } },
  { name: "一色三同顺2", hand: "1p 2p 3p 1p 2p 3p 1m 2m 1m 1m", melds: ["c(1p 2p 3p)"], expected: ["一色三同顺", "全小", "全带幺九", "平和", "喜相逢", "缺一门", "自摸"], ctx: { winTile: "3m" } },
  { name: "一色三同顺3", hand: "1p 2p 3p 1p 2p 3p 1m 3m 1m 1m", melds: ["c(1p 2p 3p)"], expected: ["一色三同顺", "全小", "全带幺九", "平和", "喜相逢", "缺一门", "自摸"], ctx: { winTile: "2m" } },
  { name: "一色三同顺4", hand: "1p 2p 3p 1p 2p 3p 1m 2m 9m 9m", melds: ["c(1p 2p 3p)"], expected: ["一色三同顺", "全带幺九", "平和", "喜相逢", "缺一门", "边张", "自摸"], ctx: { winTile: "3m" } },
  { name: "一色三节高1", hand: "1p 2p 3p 1p 2p 3p 1p 2p 3p 1m 2m 3m 1m", melds: [], expected: ["一色三节高", "全小", "三暗刻", "不求人", "幺九刻", "缺一门"], ctx: { winTile: "1m" } },
  { name: "一色三节高2", hand: "1p 2p 1p 2p 1p 2p 1m 2m 3m 1m", melds: ["p(3p 3p 3p)"], expected: ["一色三节高", "全小", "双暗刻", "自摸", "幺九刻", "缺一门"], ctx: { winTile: "1m" } },
  { name: "一色三节高3", hand: "1p 1p 1p 1m 2m 3m 1m", melds: ["p(3p 3p 3p)", "p(2p 2p 2p)"], expected: ["一色三节高", "全小", "自摸", "幺九刻", "缺一门"], ctx: { winTile: "1m" } },
  { name: "一色三节高4", hand: "5s 5s 5s 6s 6s 6s 7s 7s 7s 7s 8s 9s Z", melds: [], expected: ["一色三节高", "三暗刻", "混一色", "不求人", "四归一", "单钓将"], ctx: { winTile: "Z" } },
  { name: "一色三节高5", hand: "5s 5s 5s 6s 6s 6s 7s 7s 7s 8s 9s Z Z", melds: [], expected: ["一色三节高", "三暗刻", "混一色", "门前清", "四归一"], ctx: { winTile: "7s", winSource: "discard" } },
  { name: "一色三节高6", hand: "2p 2p 2p 3p 3p 3p 4p 4p 9p 9p 2s 3s 4s", melds: [], expected: ["一色三节高", "三暗刻", "不求人", "缺一门", "无字"], ctx: { winTile: "4p" } },
  { name: "全大1?", hand: "7m 8m 9m 7p 8p 9p 7s 8s 9s 7m 8m 9m 9p", melds: [], expected: ["全大", "三色三同顺", "全带幺九", "不求人", "平和", "一般高"], ctx: { winTile: "9p" } },
  { name: "全大2?", hand: "7m 8m 9m 7p 8p 9p 7s 8s 9s 8m 9m 9p 9p", melds: [], expected: ["全大", "三色三同顺", "全带幺九", "门前清", "平和", "一般高", "边张"], ctx: { winTile: "7m", winSource: "discard" } },
  { name: "全大3?", hand: "7m 8m 9m 7p 8p 9p 7s 8s 9s 7m 9m 9p 9p", melds: [], expected: ["全大", "三色三同顺", "全带幺九", "门前清", "平和", "一般高", "坎张"], ctx: { winTile: "8m", winSource: "discard" } },
  { name: "全中1", hand: "4p 4p 4p 5s 5s 5s 6m 6m 6m 4s 4s 4s 6p", melds: [], expected: ["四暗刻", "全中", "三色三节高", "不求人", "双同刻"], ctx: { winTile: "6p" } },
  { name: "全中2", hand: "6m 6m 6p 4s 4s 4s 6p", melds: ["p(4p 4p 4p)", "p(5s 5s 5s)"], expected: ["全中", "三色三节高", "碰碰和", "双同刻", "双暗刻", "自摸"], ctx: { winTile: "6m" } },
  { name: "全小1", hand: "1p 2p 3p 1p 2p 3p 1p 2p 3p 1p 2p 3p 1m", melds: [], expected: ["一色四同顺", "全小", "全带幺九", "不求人", "平和", "缺一门", "单钓将"], ctx: { winTile: "1m" } },
  { name: "全小2", hand: "1p 2p 3p 1p 2p 3p 1m", melds: ["c(1p 2p 3p)", "c(1p 2p 3p)"], expected: ["一色四同顺", "全小", "全带幺九", "平和", "缺一门", "单钓将"], ctx: { winTile: "1m", winSource: "discard" } },
  { name: "清龙1", hand: "1m 2m 3m 4m 5m 6m 7m 8m 9m 1s 2s 3s 8s", melds: [], expected: ["清龙", "不求人", "平和", "喜相逢", "缺一门", "单钓将"], ctx: { winTile: "8s" } },
  { name: "清龙2", hand: "1m 2m 3m 4m 5m 6m 7m 8m 8s 8s", melds: ["c(1s 2s 3s)"], expected: ["清龙", "平和", "喜相逢", "缺一门"], ctx: { winTile: "9m", winSource: "discard" } },
  { name: "三色双龙会1", hand: "1m 2m 3m 7m 8m 9m 1s 2s 3s 7s 8s 9s 5p", melds: [], expected: ["三色双龙会", "不求人", "单钓将"], ctx: { winTile: "5p" } },
  { name: "三色双龙会2", hand: "1m 2m 3m 1s 2s 3s 8s 9s 5p 5p", melds: ["c(7m 8m 9m)"], expected: ["三色双龙会", "边张"], ctx: { winTile: "7s", winSource: "discard" } },
  { name: "一色三步高1", hand: "3p 4p 5p 4p 5p 6p 5p 6p 7p 2m 3m 4m 9s", melds: [], expected: ["一色三步高", "不求人", "平和", "单钓将"], ctx: { winTile: "9s" } },
  { name: "一色三步高2", hand: "1s 2s 3s 4s 5s 2m 3m 4m 9p 9p", melds: ["c(5s 6s 7s)"], expected: ["一色三步高", "平和"], ctx: { winTile: "3s", winSource: "discard" } },
  { name: "全带五", hand: "4m 5m 6m 4p 5p 6p 3s 4s 5s 5s 6s 7s 5s", melds: [], expected: ["全带五", "不求人", "平和", "四归一", "喜相逢"], ctx: { winTile: "5s" } },
  { name: "三同刻1", hand: "4m 4m 4m 4p 4p 4p 4s 4s 4s 6s 6s 6m 6m", melds: [], expected: ["四暗刻", "全双刻", "全中", "三同刻", "不求人"], ctx: { winTile: "6s" } },
  { name: "三同刻2", hand: "4s 4s 4s 6s 6s 6m 6m", melds: ["p(4m 4m 4m)", "k(4p 4p 4p 4p)"], expected: ["全双刻", "全中", "三同刻", "双暗刻", "明杠", "自摸"], ctx: { winTile: "6s" } },
  { name: "全不靠1", hand: "1m 4m 7m 2p 5p 8p 3s 6s 9s E S W N", melds: [], expected: ["全不靠", "组合龙", "不求人"], ctx: { winTile: "Z" } },
  { name: "全不靠2", hand: "1m 4m 7m 2p 5p 3s 6s 9s E S W N F", melds: [], expected: ["全不靠"], ctx: { winTile: "Z", winSource: "discard" } },
  { name: "组合龙1", hand: "1m 4m 7m 2s 5s 8s 3p 6p 9p 6m 7m 8m 9s", melds: [], expected: ["组合龙", "不求人", "平和", "单钓将"], ctx: { winTile: "9s" } },
  { name: "组合龙2", hand: "1p 4p 7p 2m 5m 8m 3s 9s 9s 9s", melds: ["c(6m 7m 8m)"], expected: ["组合龙", "平和", "自摸"], ctx: { winTile: "6s" } },
  { name: "组合龙3", hand: "1m 4m 7m 2s 5s 8s 3p 6p 9p Z Z W W", melds: [], expected: ["组合龙", "五门齐", "箭刻", "门前清"], ctx: { winTile: "Z", winSource: "discard" } },
  { name: "大于五", hand: "6m 7m 8m 6p 7p 8p 6m 7m 8m 9p", melds: ["c(6s 7s 8s)"], expected: ["大于五", "三色三同顺", "平和", "一般高", "自摸"], ctx: { winTile: "9p" } },
  { name: "小于五1", hand: "1p 1p 1p 2p 2p 2p 3p 3p 3p 3p 4p 4p 4p", melds: [], expected: ["清一色", "一色三节高", "三暗刻", "小于五", "推不倒", "不求人", "四归一", "四归一", "幺九刻"], ctx: { winTile: "2p" } },
  { name: "小于五2", hand: "2p 2p 2p 3p 3p 3p 2p 3p 4p 4p", melds: ["p(1p 1p 1p)"], expected: ["清一色", "一色三节高", "双暗刻", "小于五", "推不倒", "四归一", "四归一", "幺九刻"], ctx: { winTile: "4p", winSource: "discard" } },
  { name: "三风刻1", hand: "E E E S S W W W F F F B B", melds: [], expected: ["字一色", "四暗刻", "三风刻", "不求人", "箭刻", "圈风刻", "门风刻"], ctx: { winTile: "S" } },
  { name: "三风刻2", hand: "S S W W W B B", melds: ["p(F F F)", "p(E E E)"], expected: ["字一色", "三风刻", "箭刻", "门风刻"], ctx: { winTile: "S", roundWind: "north", seatWind: "south", winSource: "discard"} },
  { name: "花龙1", hand: "1m 2m 3m 4p 5p 6p 7s 8s 9s 1p 2p Z Z", melds: [], expected: ["花龙", "不求人", "喜相逢", "边张"], ctx: { winTile: "3p" } },
  { name: "花龙2", hand: "4p 6p 7s 8s 9s 2p 2p", melds: ["c(1m 2m 3m)", "c(1p 2p 3p)"], expected: ["花龙", "平和", "喜相逢", "坎张"], ctx: { winTile: "5p", winSource: "discard" } },
  { name: "推不倒1", hand: "3p 4p 5p 9p 9p 9p 4s 5s 6s 9s 9s 9s 3p", melds: [], expected: ["推不倒", "不求人", "双同刻", "双暗刻", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "3p" } },
  { name: "推不倒2", hand: "3p 4p 5p 4s 5s 6s 9s 9s 9s 3p", melds: ["p(9p 9p 9p)"], expected: ["推不倒", "双同刻", "幺九刻", "幺九刻", "无字"], ctx: { winTile: "3p", winSource: "discard" } },
  { name: "推不倒2", hand: "1p 1p 2p 2p 3p 3p 4p 4p 5p 5p 8p 8p 9p", melds: [], expected: ["推不倒", "七对", "清一色", "不求人"], ctx: { winTile: "9p" } },
  { name: "三色三同顺", hand: "1m 2m 3m 1p 2p 3p 1s 2s 3s 4s 5s 6s 7m", melds: [], expected: ["三色三同顺", "不求人", "平和", "连六", "单钓将"], ctx: { winTile: "7m" } },
  { name: "三色三节高1", hand: "7m 7m 7m 9s 9s 9p 9p", melds: ["p(8p 8p 8p)", "p(8m 8m 8m)"], expected: ["全大", "三色三节高", "碰碰和", "双同刻", "双暗刻", "自摸", "幺九刻"], ctx: { winTile: "9s" } },
  { name: "三色三节高2", hand: "9m 9m 9m 8s 8s 8s E", melds: ["p(7p 7p 7p)", "p(6m 6m 6m)"], expected: ["单钓将", "三色三节高", "碰碰和", "双暗刻", "自摸", "幺九刻"], ctx: { winTile: "E" } },
  { name: "无番和1", hand: "1m 2m 3m 7s 8s B B", melds: ["c(3m 4m 5m)", "p(2p 2p 2p)"], expected: ["无番和"], ctx: { winTile: "6s", winSource: "discard", bonusTileCount: 2 } },
  { name: "无番和2", hand: "1m 2m 3m 7s 8s B B", melds: ["c(3m 4m 5m)", "p(2p 2p 2p)"], expected: ["无番和"], ctx: { winTile: "9s", winSource: "discard" } },
  { name: "妙手回春1", hand: "1m 2m 3m 2p 3p 4p 7s 8s 9s 2p 3p E E", melds: [], expected: ["妙手回春", "不求人", "一般高"], ctx: { winTile: "4p", wallCount: 0 } },
  { name: "妙手回春1", hand: "1m 2m 3m 2p 3p 4p 2p 4p E E", melds: ["c(3s 4s 5s)"], expected: ["妙手回春", "三色三步高", "一般高", "坎张"], ctx: { winTile: "3p", wallCount: 0 } },
  { name: "海底捞月", hand: "1m 2m 3m 4p 5p 6p 7s 8s 9s 2p 3p E E", melds: [], expected: ["花龙", "门前清", "海底捞月"], ctx: { winTile: "4p", winSource: "discard", wallCount: 0 } },
  { name: "杠上开花1", hand: "1m 2m 3m 4p 5p 7p 7p", melds: ["k(9s 9s 9s 9s)", "p(E E E)"], expected: ["杠上开花", "圈风刻", "门风刻", "幺九刻", "明杠"], ctx: { winTile: "6p", winSource: "kongDraw" } },
  { name: "杠上开花2", hand: "1m 2m 3m 4p 5p 7p 7p", melds: ["!k(9s 9s 9s 9s)", "p(E E E)"], expected: ["杠上开花", "圈风刻", "门风刻", "幺九刻", "暗杠"], ctx: { winTile: "6p", winSource: "kongDraw" } },
  { name: "抢杠和", hand: "1m 2m 3m 4p 5p 7p 7p", melds: ["c(7s 8s 9s)", "p(N N N)"], expected: ["花龙", "抢杠和"], ctx: { winTile: "6p", winSource: "robbingKong" } },
  { name: "碰碰和1", hand: "3p 3p 3p 4p 4p 4p 5p 5p 5p B", melds: ["p(5s 5s 5s)"], expected: ["一色三节高", "三暗刻", "推不倒", "双同刻", "碰碰和", "单钓将"], ctx: { winTile: "B", winSource: "discard" } },
  { name: "碰碰和2", hand: "4p 4p 4p 5p 5p B B", melds: ["p(5s 5s 5s)", "p(3p 3p 3p)"], expected: ["一色三节高", "碰碰和", "双同刻", "双暗刻", "推不倒", "自摸"], ctx: { winTile: "5p" } },
  { name: "混一色", hand: "1m 2m 3m 5m 5m 5m 7m 8m 9m Z Z Z E", melds: [], expected: ["混一色", "不求人", "箭刻", "双暗刻", "老少副", "单钓将"], ctx: { winTile: "E" } },
  { name: "三色三步高", hand: "3m 4m 5m 4p 5p 6p 5s 7s 5p 5p", melds: ["p(5m 5m 5m)"], expected: ["全带五", "三色三步高", "四归一", "坎张", "自摸"], ctx: { winTile: "6s" } },
  { name: "五门齐", hand: "1m 2m 3m 1p 2p 3p 7s 8s 9s F F N N", melds: [], expected: ["五门齐", "全带幺九", "箭刻", "门前清", "喜相逢"], ctx: { winTile: "F", winSource: "discard" } },
  { name: "明暗杠1", hand: "1m 2m 3m 4m 5m 6m 7m", melds: ["k(2p 2p 2p 2p)", "!k(B B B B)"], expected: ["明暗杠", "箭刻", "连六", "缺一门", "自摸"], ctx: { winTile: "7m" } },
  { name: "双明杠", hand: "9m", melds: ["k(1m 1m 1m 1m)", "k(2m 2m 2m 2m)", "p(4m 4m 4m)", "p(8m 8m 8m)"], expected: ["清一色", "碰碰和", "全求人", "双明杠", "幺九刻"], ctx: { winTile: "9m", winSource: "discard" } },
];
